# Generated by Django 3.1 on 2020-08-29 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
