# Generated by Django 3.1 on 2020-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='mission')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField()),
            ],
        ),
    ]
