# Generated by Django 3.1 on 2020-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_missionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Directors Only', 'Directors Only')], default='Public', max_length=30),
        ),
    ]
