# Generated by Django 3.1 on 2020-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0009_auto_20200920_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endowment',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='endowment',
            name='description',
        ),
        migrations.AddField(
            model_name='endowment',
            name='email',
            field=models.EmailField(default='youremail@yourdomain.com',
                                    max_length=254),
        ),
        migrations.AddField(
            model_name='endowment',
            name='endowment_type',
            field=models.CharField(
                choices=[('House', 'House'), ('Land', 'Land')],
                default='House', max_length=50),
        ),
    ]
