# Generated by Django 3.1 on 2020-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
