# Generated by Django 3.1 on 2020-10-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_advertisement_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsgallery')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.newspost')),
            ],
        ),
    ]
