# Generated by Django 3.1 on 2020-10-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0016_auto_20201006_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_full',
            field=models.BooleanField(default=True,
                                      help_text='Make it true, if want to keep it full width on homepage'),
        ),
        migrations.CreateModel(
            name='HomepageManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('chairman_name', models.CharField(max_length=200)),
                ('chairman_message', models.TextField()),
                ('chairman_photo',
                 models.ImageField(upload_to='chairmanphoto')),
                ('message_link', models.URLField()),
                ('project_1',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='project1', to='cms.project')),
                ('project_2',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='project2', to='cms.project')),
                ('project_3',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='project3', to='cms.project')),
            ],
        ),
    ]
