# Generated by Django 3.1 on 2020-10-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0018_remove_project_is_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='year',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='short_description',
        ),
        migrations.AddField(
            model_name='history',
            name='is_chairman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
