# Generated by Django 3.1 on 2020-10-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20201006_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endowment',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Endowment Type', 'verbose_name_plural': 'Endowment Types'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
