# Generated by Django 3.1 on 2020-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_project_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(default='icon/donateclassroom.png', upload_to='icon'),
        ),
    ]
