# Generated by Django 3.1 on 2020-10-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0025_auto_20201008_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='featured_project',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='cms.project'),
        ),
    ]
