# Generated by Django 3.1 on 2020-10-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20201013_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='about_description',
            field=models.TextField(default=''),
        ),
    ]
