# Generated by Django 3.1 on 2020-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0028_contentmanagement_about_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='end_year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='start_year',
            field=models.BigIntegerField(default=1990),
        ),
    ]
