# Generated by Django 3.1 on 2020-10-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0030_popup_short_desc_for_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_page_banner',
            field=models.ImageField(default='', upload_to='doantebanner'),
        ),
    ]
