# Generated by Django 3.1 on 2020-10-20 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0031_contentmanagement_donate_page_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmanagement',
            name='donate_page_banner',
        ),
    ]
