# Generated by Django 3.1 on 2020-10-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_remove_contentmanagement_donate_page_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_page_banner',
            field=models.ImageField(blank=True, null=True, upload_to='doantebanner'),
        ),
    ]
