# Generated by Django 3.1 on 2020-10-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0033_contentmanagement_donate_page_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='sponsorship_banner',
            field=models.ImageField(blank=True, null=True,
                                    upload_to='sponsorshipbanner'),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='sponsorship_banner_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='sponsorship_become_sponsor_image',
            field=models.ImageField(blank=True, null=True,
                                    upload_to='sponsorshipbanner'),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='sponsorship_become_sponsor_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='sponsorship_become_sponsor_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
