# Generated by Django 3.1 on 2020-10-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0034_auto_20201020_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='workwithus_banner',
            field=models.ImageField(blank=True, null=True,
                                    upload_to='workwithusbanner'),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='workwithus_banner_text_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='workwithus_banner_text_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='workwithus_banner_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
