# Generated by Django 3.1 on 2020-10-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20201020_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.newscategory'),
        ),
    ]
