# Generated by Django 3.1 on 2020-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0037_newspost_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'News Categories'},
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step1_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step1_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step2_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step2_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step3_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='donate_step3_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
