# Generated by Django 3.1 on 2020-10-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20201020_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInvolvedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='getinvolved')),
                ('caption', models.CharField(max_length=500)),
            ],
        ),
    ]
