# Generated by Django 3.1 on 2020-10-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_getinvolvedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagement',
            name='getinvolved_banner',
            field=models.ImageField(blank=True, null=True, upload_to='getinvolvedbanner'),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='getinvolved_banner_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contentmanagement',
            name='getinvolved_banner_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
