# Generated by Django 3.1 on 2020-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0041_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy',
                     'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('Terms', 'Terms of Use'),
                                            ('Privacy', 'Privacy Policy'),
                                            ('Refund', 'Refund Policy')],
                                   default='Terms', max_length=30),
        ),
    ]
