# Generated by Django 3.1 on 2020-08-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('micomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.micomodel')),
                ('thumbnail', models.ImageField(upload_to='causes')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('goal', models.IntegerField()),
            ],
            bases=('common.micomodel',),
        ),
    ]
