# Generated by Django 3.1 on 2020-09-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_remove_advertisement_link'),
        ('common', '0001_initial'),
        ('donations', '0002_causes_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDonation',
            fields=[
                ('micomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.micomodel')),
                ('duration', models.CharField(choices=[('One Time', 'One Time'), ('Monthly', 'Monthly')], max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(choices=[('Paypal', 'Paypal'), ('Card', 'Card'), ('Check', 'Check')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.project')),
            ],
            bases=('common.micomodel',),
        ),
        migrations.CreateModel(
            name='CausesDonation',
            fields=[
                ('micomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.micomodel')),
                ('duration', models.CharField(choices=[('One Time', 'One Time'), ('Monthly', 'Monthly')], max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(choices=[('Paypal', 'Paypal'), ('Card', 'Card'), ('Check', 'Check')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='causedonation', to='donations.causes')),
            ],
            bases=('common.micomodel',),
        ),
    ]
