# Generated by Django 3.1 on 2020-09-29 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('donations', '0003_causesdonation_projectdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='causesdonation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
