# Generated by Django 3.1 on 2020-10-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
        ('donations', '0006_auto_20200929_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('micomodel_ptr', models.OneToOneField(auto_created=True,
                                                       on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True,
                                                       primary_key=True,
                                                       serialize=False,
                                                       to='common.micomodel')),
                ('order_id', models.CharField(max_length=100)),
                ('response_code', models.CharField(max_length=10)),
                ('reason_code', models.CharField(max_length=10)),
                ('reason_code_desc', models.CharField(max_length=500)),
                ('reference_no', models.CharField(max_length=100)),
                ('padded_card_no', models.CharField(max_length=100)),
                ('auth_code', models.CharField(max_length=100)),
                ('cvv2_result', models.CharField(max_length=100)),
                ('auth_result', models.CharField(max_length=100)),
                ('cavv_value', models.CharField(max_length=200)),
                ('eci_indicator', models.CharField(max_length=200)),
                ('transaction_stain', models.CharField(max_length=500)),
                ('original_response', models.CharField(max_length=20)),
                ('signature', models.CharField(max_length=500)),
            ],
            bases=('common.micomodel',),
        ),
    ]
