# Generated by Django 3.1 on 2020-10-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='auth_result',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cavv_value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eci_indicator',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_stain',
        ),
    ]
