# Generated by Django 3.1 on 2020-10-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20201008_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='causes',
            name='icon',
            field=models.ImageField(default='/static/donateclassroom.png', upload_to='icon'),
        ),
    ]
