# Generated by Django 3.1 on 2020-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_auto_20201008_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causesdonation',
            name='method',
            field=models.CharField(choices=[('paypal', 'paypal'), ('card', 'card'), ('offline', 'offline')], max_length=50),
        ),
    ]
