# Generated by Django 3.1 on 2020-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('donations', '0015_auto_20201021_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
